function cheatSheet

f = figure(2);
set(f, 'color', [1 1 1], 'menubar', 'none', 'toolbar', 'none', ...
  'KeyPressFcn', {'keyPress'}, ...
  'numbertitle', 'off', 'name', 'BenWare keys');
clf;
p = get(f, 'position');
set(f,'position', [p(1) p(2), 350, 300]);
put_fig_in_top_right;
p = get(f, 'position');

xoffset = 40;
yoffset = 20;
t = uicontrol(2,'style','text', ...
  'string','BenWare keys','position', ...
  [xoffset-10 p(4)-yoffset-95 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left', 'fontweight', 'bold');

t = uicontrol(2,'style','text', ...
  'string','w -- display waveform','position', ...
  [xoffset p(4)-yoffset-120 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','r -- display raster','position', ...
  [xoffset p(4)-yoffset-140 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','p -- display PSTH','position', ...
  [xoffset p(4)-yoffset-160 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','f -- toggle waveform filtering on/off','position', ...
  [xoffset p(4)-yoffset-180 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','a -- show only the active channel (toggle on/off)','position', ...
  [xoffset p(4)-yoffset-200 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','o -- turn plotting on/off altogether','position', ...
  [xoffset p(4)-yoffset-220 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','space -- pause after the current sweep','position', ...
  [xoffset p(4)-yoffset-240 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','q -- stop after the current sweep','position', ...
  [xoffset p(4)-yoffset-260 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','up/down arrows -- increase/decrease gain by 25%','position', ...
  [xoffset p(4)-yoffset-280 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');

t = uicontrol(2,'style','text', ...
  'string','k -- show/hide this list','position', ...
  [xoffset p(4)-yoffset-300 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');
  
t = uicontrol(2,'style','text', ...
  'string','Click on a plot to choose the active channel','position', ...
  [xoffset p(4)-yoffset-330 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');
