function cheatSheet


keyList = {'w -- display waveform', ...
  'r -- display raster', ...
  'p -- display pooled PSTH', ...
  '0-9 -- display per-set PSTH', ...
  'l -- display average waveform (LFP)', ...
  'f -- toggle waveform filtering on/off', ...
  'a -- show only the active channel (toggle on/off)', ...
  'o -- turn plotting on/off altogether', ...
  'space -- pause after the current sweep', ...
  'q -- stop after the current sweep', ...
  'up/down -- increase/decrease gain by 25%', ...
  'delete -- reset the PSTH and LFP plots', ...
  'k -- show/hide this list'};

xoffset = 40;
yoffset = 20;

f = figure(102);
set(f, 'color', [1 1 1], 'menubar', 'none', 'toolbar', 'none', ...
  'KeyPressFcn', {'keyPress'}, ...
  'numbertitle', 'off', 'name', 'BenWare keys');
clf;
p = get(f, 'position');
set(f,'position', [p(1) p(2), 380, 90+length(keyList)*yoffset]);
put_fig_in_top_right;
set(gcf, 'position',get(gcf, 'position') - [8 28 0 0]);
p = get(f, 'position');


t = uicontrol(f, 'style', 'text', ...
  'string', 'BenWare keys', ...
  'position', [xoffset-10 p(4)-yoffset-95 500 100], ...
  'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left', 'fontweight', 'bold');
  
y = -120;
for txt = keyList
  txt = txt{1};
  idx = findstr(' -- ', txt);
  t = uicontrol(f, 'style', 'text', ...
    'string', txt(1:idx-1), 'position', [xoffset p(4)-yoffset+y 500 100], ...
    'backgroundcolor', [1 1 1], ...
    'horizontalalignment', 'left', 'fontweight', 'bold');
  t = uicontrol(f, 'style', 'text', ...
    'string', txt(idx+4:end), 'position', [xoffset+70 p(4)-yoffset+y 500 100], ...
    'backgroundcolor', [1 1 1], ...
    'horizontalalignment', 'left');
  y = y-20;
end

y = y - 10;
t = uicontrol(f, 'style', 'text', ...
  'string', 'Click on a plot to choose the active channel', ...
  'position', [xoffset p(4)-yoffset+y 500 100], 'backgroundcolor', [1 1 1], ...
  'horizontalalignment', 'left');
